# Generated by Django 3.2.6 on 2021-12-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211007_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='studentdept',
            field=models.CharField(choices=[('', 'Department'), ('Not Applicable', 'Not Applicable'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil '), ('Electrical', 'Electrical'), ('Computer Science', 'Computer Science'), ('Electronics & Communication', 'Electronics & Communication')], default='Computer Science', max_length=40),
        ),
        migrations.AlterField(
            model_name='academic',
            name='studentsemester',
            field=models.CharField(choices=[('', 'Semester'), ('Not Applicable', 'Not Applicable'), ('1st Semester', 'First Semester'), ('2nd Semester', 'Second Semester '), ('3rd Semester', 'Third Semester'), ('4th Semester', 'Fourth Semester'), ('5th Semester', 'Fifth Semester'), ('6th Semester', 'Sixth Semester'), ('7th Semester', 'Seventh Semester'), ('8th Semester', 'Eightth Semester')], default='First Semester', max_length=40),
        ),
        migrations.AlterField(
            model_name='academic',
            name='studentyear',
            field=models.CharField(choices=[('', 'Year'), ('Not Applicable', 'Not Applicable'), ('1st Year', 'First Year'), ('2nd Year', 'Second Year '), ('3rd Year', 'Third Year'), ('4t Year', 'Fourth Year')], default='First Year', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(choices=[('', 'Department'), ('Not Applicable', 'Not Applicable'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil '), ('Electrical', 'Electrical'), ('Computer Science', 'Computer Science'), ('Electronics & Communication', 'Electronics & Communication')], default='Computer Science', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.CharField(choices=[('', 'Semester'), ('Not Applicable', 'Not Applicable'), ('1st Semester', 'First Semester'), ('2nd Semester', 'Second Semester '), ('3rd Semester', 'Third Semester'), ('4th Semester', 'Fourth Semester'), ('5th Semester', 'Fifth Semester'), ('6th Semester', 'Sixth Semester'), ('7th Semester', 'Seventh Semester'), ('8th Semester', 'Eightth Semester')], default='First Semester', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(choices=[('', 'Year'), ('Not Applicable', 'Not Applicable'), ('1st Year', 'First Year'), ('2nd Year', 'Second Year '), ('3rd Year', 'Third Year'), ('4t Year', 'Fourth Year')], default='First Year', max_length=40),
        ),
    ]
